# Learn datasciene together- group discussion 1

* Numpy is a python package, stand for numerical python, similar to scipy for scintific python
* Numpy comes along with python, most of the times, if not, we can install:
   * !pip install numpy

In [106]:
#lets import numpy in our program as np
import numpy as np

In [107]:
# array creation, put data on an array

In [108]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [109]:
#print the shape
print(np.shape(a))

#or you can also use print(a.shape)

(3,)


In [110]:
#lets reshape array in proper array or matrix of size 3,1
b=np.reshape(a,(3,1))

In [111]:
#now it in shape of (3,1), i.e a matrix of 3 rows and one columns
print("shape of new array",b.shape)
print("The element of the array", b)

shape of new array (3, 1)
The element of the array [[1]
 [2]
 [3]]


In [112]:
#Here is the another function "resize" which works as same as np.reshape
x=np.resize(a,(3,1))

In [113]:
print(x.shape)

(3, 1)


In [114]:
#lets try few ther
a=np.arange(100).reshape(10,10)

In [115]:
# for easy creation of numpy array, we can use np.arange() function.

In [116]:
#We can combine above two function in one line: creation and reshape
a=np.arange(100, dtype='float').reshape(20,5)

In [117]:
print(a)

[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]
 [20. 21. 22. 23. 24.]
 [25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34.]
 [35. 36. 37. 38. 39.]
 [40. 41. 42. 43. 44.]
 [45. 46. 47. 48. 49.]
 [50. 51. 52. 53. 54.]
 [55. 56. 57. 58. 59.]
 [60. 61. 62. 63. 64.]
 [65. 66. 67. 68. 69.]
 [70. 71. 72. 73. 74.]
 [75. 76. 77. 78. 79.]
 [80. 81. 82. 83. 84.]
 [85. 86. 87. 88. 89.]
 [90. 91. 92. 93. 94.]
 [95. 96. 97. 98. 99.]]


In [118]:
#we can also use numpy function ones and zeros to create array with all element either ones or zeros
b=np.ones(shape=(5,5), dtype='float')


In [119]:
# another way of creating array of zeros and ones, which is sometime useful.
zero=np.zeros((2,2), dtype='float')

In [120]:
# slicing and indexing of numpy array

In [121]:
a = np.arange((100)).reshape(10,10)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [122]:
#lets assign a specific value to a slice of array
b=a[1:2,2:3]=5

<center> *** Good Luck*** ** see you next saturday</center>